export const routesV2 = {
  "Littleroot Town": {
    "Surfing (44)": {
      Squirtle: "60%",
      Totodile: "30%",
      Croconaw: "5%",
      Wartortle: "5%",
    },
    "Old Rod (4-5)": { Luvdisc: "70%", Goldeen: "30%" },
    "Good Rod (20)": {
      Corphish: "60%",
      Goldeen: "20%",
      Poliwhirl: "20%",
    },
    "Super Rod (65)": {
      Luvdisc: "41%",
      Seaking: "40%",
      Poliwhirl: "15%",
      Crawdaunt: "4%",
    },
  },
  "Route 103": {
    "Grass (4)": {
      Sunkern: "20%",
      Wingull: "20%",
      Ledyba: "10%",
      Spearow: "10%",
      Skitty: "10%",
      Ekans: "10%",
      Mareep: "5%",
      Hoppip: "5%",
      Poliwag: "4%",
      Spoink: "4%",
      Aipom: "1%",
      Taillow: "1%",
    },
    "Surfing (43)": {
      Kingler: "60%",
      Seaking: "30%",
      Qwilfish: "5%",
      Mantine: "5%",
    },
    "Old Rod (5)": { Remoraid: "70%", Tentacool: "30%" },
    "Good Rod (20)": { Octillery: "80%", Tentacool: "20%" },
    "Super Rod (65)": {
      Qwilfish: "40%",
      Octillery: "40%",
      Kingler: "15%",
      Seaking: "5%",
    },
  },
  "Oldale Town": {
    "Grass (2-5)": {
      Vulpix: "21%",
      Slugma: "20%",
      Numel: "20%",
      Growlithe: "20%",
      Ponyta: "6%",
      Magby: "5%",
      Cyndaquil: "4%",
      Charmander: "4%",
    },
  },
  "Route 102": {
    "Grass (4-7)": {
      Meowth: "20%",
      Sandshrew: "20%",
      "Nidoran♂": "10%",
      Electrike: "10%",
      Hoothoot: "10%",
      Gulpin: "10%",
      Spinarak: "5%",
      Spoink: "5%",
      "Farfetch’d": "4%",
      Ralts: "4%",
      Minun: "1%",
      Pikachu: "1%",
    },
    "Surfing (43)": {
      Luvdisc: "60%",
      Seaking: "30%",
      Carvanha: "5%",
      Poliwrath: "4%",
      Politoed: "1%",
    },
    "Old Rod (5)": { Carvanha: "70%", Barboach: "30%" },
    "Good Rod (23)": { Psyduck: "60%", Goldeen: "20%", Corphish: "20%" },
    "Super Rod (65)": { Golduck: "40%", Whiscash: "40%", Seaking: "20%" },
  },
  "Petalburg City": {
    "Grass (7)": {
      Krabby: "20%",
      Corphish: "20%",
      Poliwag: "15%",
      Psyduck: "15%",
      Surskit: "10%",
      Marill: "10%",
      Totodile: "4%",
      Squirtle: "4%",
      Slowpoke: "2%",
    },
    "Surfing (43)": {
      Crawdaunt: "60%",
      Golduck: "30%",
      Whiscash: "5%",
      Azumarill: "4%",
      Poliwhirl: "1%",
    },
    "Old Rod (5)": { Azurill: "70%", Luvdisc: "30%" },
    "Good Rod (20)": { Marill: "60%", Goldeen: "20%", Corphish: "20%" },
    "Super Rod (65)": {
      Golduck: "40%",
      Seaking: "40%",
      Poliwhirl: "15%",
      Crawdaunt: "4%",
      Azumarill: "1%",
    },
  },
  "Route 104": {
    "Grass (7)": {
      Jigglypuff: "20%",
      Cubone: "20%",
      Seedot: "10%",
      Snubbull: "10%",
      "Nidoran♀": "10%",
      Natu: "10%",
      Mareep: "5%",
      Spoink: "5%",
      Hoothoot: "4%",
      Venonat: "4%",
      Drowzee: "1%",
      Elekid: "1%",
    },
    "Surfing (43)": {
      Seaking: "60%",
      Pelipper: "30%",
      Swellow: "5%",
      Pidgeot: "4%",
      Wartortle: "1%",
    },
    "Old Rod (8)": { Magikarp: "100%" },
    "Good Rod (20)": { Magikarp: "100%" },
    "Super Rod (65)": { Magikarp: "99%", Gyarados: "1%" },
  },
  "Petalburg Woods": {
    "Grass (7-8)": {
      Oddish: "20%",
      Hoothoot: "20%",
      Phanpy: "10%",
      Teddiursa: "10%",
      Bellsprout: "10%",
      Pineco: "10%",
      Illumise: "5%",
      Volbeat: "5%",
      Cascoon: "4%",
      Silcoon: "4%",
      Mankey: "1%",
      Slakoth: "1%",
    },
  },
  "Route 115": {
    "Grass (19-43)": {
      Swablu: "20%",
      Clefairy: "20%",
      Eevee: "10%",
      Absol: "10%",
      Wigglytuff: "10%",
      Swellow: "10%",
      Beldum: "9%",
      Kangaskhan: "5%",
      Bagon: "4%",
      Shelgon: "1%",
      Metang: "1%",
    },
    "Surfing (43)": {
      Tentacool: "60%",
      Qwilfish: "30%",
      Relicanth: "5%",
      Kabuto: "4%",
      Omanyte: "1%",
    },
    "Old Rod (9)": { Kabuto: "70%", Omanyte: "30%" },
    "Good Rod (20)": { Kabuto: "60%", Relicanth: "20%", Omanyte: "20%" },
    "Super Rod (65)": {
      Kabutops: "44%",
      Relicanth: "40%",
      Omastar: "16%",
    },
  },
  "Route 116": {
    "Grass (9)": {
      Grimer: "20%",
      Makuhita: "20%",
      Yanma: "10%",
      Natu: "10%",
      Paras: "10%",
      Voltorb: "10%",
      Spoink: "5%",
      Chimecho: "5%",
      Ralts: "4%",
      Unown: "4%",
      Kakuna: "1%",
      Metapod: "1%",
    },
  },
  "Rustboro City": {
    "Grass (9)": {
      Shroomish: "20%",
      Seedot: "20%",
      Cacnea: "10%",
      Bellsprout: "10%",
      Oddish: "10%",
      Hoppip: "10%",
      Sunkern: "5%",
      Roselia: "5%",
      Chikorita: "4%",
      Bulbasaur: "4%",
      Exeggcute: "1%",
      Lotad: "1%",
    },
    "Mirage Tower Claw Fossil (20)": { Anorith: "100%" },
    "Mirage Tower Root Fossil (20)": { Lileep: "100%" },
  },
  "Rusturf Tunnel": {
    "Cave (10-12)": {
      Nosepass: "20%",
      Geodude: "20%",
      Onix: "14%",
      Rhyhorn: "10%",
      Phanpy: "10%",
      Sandshrew: "10%",
      Dunsparce: "5%",
      Cubone: "5%",
      Swinub: "4%",
      Whismur: "1%",
      Zubat: "1%",
    },
  },
  "Route 106": {
    "Surfing (43)": {
      Seel: "60%",
      Spheal: "30%",
      Shellder: "5%",
      Dewgong: "4%",
      Sealeo: "1%",
    },
    "Old Rod (15)": { Seel: "100%" },
    "Good Rod (20)": { Spheal: "80%", Seel: "20%" },
    "Super Rod (65)": {
      Spheal: "40%",
      Seel: "40%",
      Sealeo: "15%",
      Dewgong: "5%",
    },
  },
  "Route 107": {
    "Surfing (43)": {
      Corsola: "60%",
      Huntail: "30%",
      Lanturn: "5%",
      Clamperl: "4%",
      Gorebyss: "1%",
    },
    "Old Rod (15)": { Clamperl: "100%" },
    "Good Rod (20)": { Shellder: "60%", Seel: "20%", Spheal: "20%" },
    "Super Rod (65)": {
      Seel: "40%",
      Spheal: "40%",
      Cloyster: "15%",
      Sealeo: "5%",
    },
  },
  "Dewford Town": {
    "Grass (3-15)": {
      Makuhita: "34%",
      Mankey: "29%",
      Machop: "20%",
      Tyrogue: "16%",
      Meditite: "1%",
    },
    "Surfing (43)": {
      Corsola: "60%",
      Seel: "30%",
      Spheal: "5%",
      Krabby: "4%",
      Slowpoke: "1%",
    },
    "Old Rod (15)": { Spheal: "70%", Shellder: "30%" },
    "Good Rod (20)": { Clamperl: "60%", Sealeo: "20%", Seel: "20%" },
    "Super Rod (65)": {
      Huntail: "40%",
      Dewgong: "40%",
      Cloyster: "15%",
      Gorebyss: "4%",
      Walrein: "1%",
    },
  },
  "Granite Cave": {
    "Cave [1F] (14-15)": {
      Aron: "25%",
      Mawile: "25%",
      Spoink: "14%",
      Clefairy: "10%",
      Spinda: "10%",
      Teddiursa: "10%",
      Ralts: "4%",
      Drowzee: "1%",
      Chimecho: "1%",
    },
    "Cave [B1F] (15)": {
      Seel: "24%",
      Smoochum: "21%",
      Delibird: "10%",
      Sneasel: "10%",
      Swinub: "10%",
      Snorunt: "10%",
      Spheal: "9%",
      Shellder: "6%",
    },
    "Cave [B2F] (16)": {
      Snorunt: "21%",
      Swinub: "21%",
      Smoochum: "15%",
      Shellder: "15%",
      Seel: "14%",
      Spheal: "14%",
    },
    "Rock Smash [B2F] (15-16)": { Geodude: "70%", Nosepass: "30%" },
    "Cave [Steven's Room] (15-16)": {
      Spoink: "20%",
      Ralts: "20%",
      Onix: "10%",
      Voltorb: "10%",
      Spinda: "10%",
      Magnemite: "10%",
      Nosepass: "5%",
      Makuhita: "5%",
      Aron: "4%",
      Dunsparce: "4%",
      Clefairy: "1%",
      Abra: "1%",
    },
  },
  "Route 109": {
    "Surfing (43)": {
      Pelipper: "60%",
      Kingler: "30%",
      Seaking: "5%",
      Wartortle: "4%",
      Blastoise: "1%",
    },
    "Old Rod (15)": { Squirtle: "100%" },
    "Good Rod (20)": { Krabby: "60%", Tentacool: "20%", Goldeen: "20%" },
    "Super Rod (65)": { Sharpedo: "56%", Wartortle: "40%", Mantine: "4%" },
  },
  "Slateport City": {
    "Grass (15)": {
      Mareep: "20%",
      Elekid: "20%",
      Voltorb: "14%",
      Electrike: "14%",
      Pikachu: "10%",
      Minun: "10%",
      Plusle: "5%",
      Pichu: "5%",
      Magnemite: "1%",
      Flaaffy: "1%",
    },
    "Surfing (43)": {
      Octillery: "60%",
      Mantine: "30%",
      Pelipper: "5%",
      Sharpedo: "4%",
      Seadra: "1%",
    },
    "Old Rod (15)": { Chinchou: "70%", Corsola: "30%" },
    "Good Rod (20)": { Mantine: "60%", Remoraid: "20%", Horsea: "20%" },
    "Super Rod (65)": {
      Sharpedo: "40%",
      Octillery: "40%",
      Lanturn: "15%",
      Mantine: "4%",
      Seadra: "1%",
    },
  },
  "Route 110": {
    "Grass (15)": {
      Delcatty: "20%",
      Roselia: "20%",
      Pidgeotto: "10%",
      Murkrow: "10%",
      Nuzleaf: "10%",
      Skiploom: "10%",
      Tropius: "5%",
      Togetic: "5%",
      Lickitung: "4%",
      Kecleon: "4%",
      Oddish: "1%",
      Poochyena: "1%",
    },
    "Surfing (43)": {
      Chinchou: "60%",
      Seaking: "30%",
      Croconaw: "5%",
      Feraligatr: "4%",
      Lanturn: "1%",
    },
    "Old Rod (16)": { Qwilfish: "70%", Remoraid: "30%" },
    "Good Rod (20)": {
      Chinchou: "60%",
      Tentacool: "20%",
      Remoraid: "20%",
    },
    "Super Rod (65)": {
      Lanturn: "40%",
      Mantine: "40%",
      Sharpedo: "16%",
      Whiscash: "4%",
    },
  },
  "Mauville City": {
    "Grass (20)": {
      Elekid: "20%",
      Pikachu: "20%",
      Voltorb: "15%",
      Magnemite: "14%",
      Mareep: "10%",
      Porygon: "10%",
      Electrike: "5%",
      Pichu: "4%",
      Flaaffy: "2%",
    },
  },
  "Route 118": {
    "Grass (41)": {
      Growlithe: "20%",
      Manectric: "20%",
      Vulpix: "10%",
      Rapidash: "10%",
      Grumpig: "10%",
      Nuzleaf: "10%",
      Weepinbell: "5%",
      Gloom: "5%",
      Nidorina: "4%",
      Nidorino: "4%",
      Pikachu: "1%",
      Exeggcute: "1%",
    },
    "Surfing (41)": {
      Tentacool: "60%",
      Chinchou: "30%",
      Mantine: "5%",
      Qwilfish: "4%",
      Octillery: "1%",
    },
    "Old Rod (20)": { Tentacool: "70%", Carvanha: "30%" },
    "Good Rod (20)": {
      Chinchou: "60%",
      Remoraid: "20%",
      Carvanha: "20%",
    },
    "Super Rod (65)": {
      Sharpedo: "40%",
      Mantine: "40%",
      Octillery: "15%",
      Qwilfish: "5%",
    },
  },
  "Route 117": {
    "Grass (20)": {
      Beautifly: "20%",
      Dustox: "20%",
      Oddish: "10%",
      Volbeat: "10%",
      Illumise: "10%",
      Ledian: "10%",
      Ariados: "5%",
      Beedrill: "5%",
      Butterfree: "4%",
      Nuzleaf: "4%",
      Shroomish: "1%",
      Vulpix: "1%",
    },
    "Surfing (43)": {
      Azumarill: "60%",
      Seaking: "30%",
      Politoed: "5%",
      Golduck: "4%",
      Poliwrath: "1%",
    },
    "Old Rod (20)": { Corphish: "70%", Krabby: "30%" },
    "Good Rod (20)": { Barboach: "60%", Goldeen: "20%", Marill: "20%" },
    "Super Rod (65)": {
      Crawdaunt: "40%",
      Kingler: "40%",
      Psyduck: "15%",
      Golduck: "5%",
    },
  },
  "Verdanturf Town": {
    "Grass (23)": {
      Sandshrew: "24%",
      Phanpy: "21%",
      Rhyhorn: "15%",
      Cubone: "14%",
      Geodude: "10%",
      Swinub: "10%",
      Numel: "5%",
      Sunflora: "1%",
    },
  },
  "Route 111": {
    "Rock Smash (5-20)": { Geodude: "100%" },
    "Desert (37-42)": {
      Trapinch: "20%",
      Diglett: "20%",
      Sandslash: "10%",
      Cacturne: "10%",
      Donphan: "10%",
      Arbok: "10%",
      Rhyhorn: "5%",
      Nidoqueen: "5%",
      Nidoking: "4%",
      Dugtrio: "4%",
      Claydol: "1%",
      Vibrava: "1%",
    },
    "Surfing (43)": {
      Poliwhirl: "60%",
      Psyduck: "30%",
      Carvanha: "5%",
      Marill: "5%",
    },
    "Old Rod (5-10)": { Magikarp: "70%", Goldeen: "30%" },
    "Good Rod (20)": { Magikarp: "60%", Goldeen: "20%", Barboach: "20%" },
    "Super Rod (65)": { Barboach: "100%" },
    "Puzzle reward": { Regirock: "100%" },
  },
  "Route 112": {
    "Grass (27)": {
      Ponyta: "20%",
      Vulpix: "20%",
      Numel: "10%",
      Spoink: "10%",
      Absol: "10%",
      Sandshrew: "10%",
      Skiploom: "5%",
      Natu: "5%",
      Snubbull: "4%",
      Growlithe: "4%",
      Flareon: "1%",
      Mightyena: "1%",
    },
  },
  "Fiery Path": {
    "Cave (27)": {
      Torkoal: "20%",
      Magcargo: "20%",
      Ponyta: "10%",
      Growlithe: "10%",
      Vulpix: "10%",
      Magby: "10%",
      Koffing: "5%",
      Quilava: "5%",
      Flareon: "4%",
      Charmeleon: "4%",
      Numel: "1%",
      Magmar: "1%",
    },
  },
  "Route 113": {
    "Grass (30)": {
      Noctowl: "20%",
      Shroomish: "20%",
      Parasect: "10%",
      Koffing: "10%",
      Rhyhorn: "10%",
      Magby: "10%",
      Phanpy: "5%",
      Teddiursa: "5%",
      Gloom: "4%",
      Numel: "4%",
      Torkoal: "1%",
      Absol: "1%",
    },
  },
  "Fallarbor Town": {
    "Grass (34)": {
      Aron: "20%",
      Sudowoodo: "20%",
      Stantler: "10%",
      Noctowl: "10%",
      Persian: "10%",
      Mawile: "10%",
      Rapidash: "5%",
      Nosepass: "5%",
      Spinda: "4%",
      Seviper: "4%",
      Zangoose: "1%",
      Golduck: "1%",
    },
  },
  "Route 114": {
    "Rock Smash (5-20)": { Geodude: "100%" },
    "Grass (34)": {
      Pikachu: "20%",
      Swablu: "20%",
      Spinda: "10%",
      Zangoose: "10%",
      Nuzleaf: "10%",
      Stantler: "10%",
      Sudowoodo: "5%",
      Electrike: "5%",
      Swalot: "4%",
      Seviper: "4%",
      Lombre: "1%",
      Lotad: "1%",
    },
    "Surfing (43)": {
      Masquerain: "60%",
      Whiscash: "30%",
      Blastoise: "5%",
      Feraligatr: "4%",
      Gyarados: "1%",
    },
    "Old Rod (35)": { Tentacool: "70%", Qwilfish: "30%" },
    "Good Rod (35)": {
      Whiscash: "60%",
      Carvanha: "20%",
      Poliwhirl: "20%",
    },
    "Super Rod (65)": {
      Magikarp: "40%",
      Barboach: "40%",
      Seaking: "15%",
      Whiscash: "4%",
      Gyarados: "1%",
    },
  },
  "Meteor Falls": {
    "Cave [1F] (35)": {
      Clefairy: "20%",
      Porygon: "20%",
      Lairon: "10%",
      Parasect: "10%",
      Golbat: "10%",
      Dunsparce: "10%",
      Loudred: "5%",
      Solrock: "5%",
      Lunatone: "4%",
      Unown: "4%",
      Cleffa: "1%",
      Clefable: "1%",
    },
    "Surfing [1F] (43)": {
      Lunatone: "60%",
      Solrock: "30%",
      Seviper: "5%",
      Gyarados: "4%",
      Whiscash: "1%",
    },
    "Old Rod [1F] (35)": { Kabuto: "70%", Omanyte: "30%" },
    "Good Rod [1F] (35)": {
      Tentacool: "60%",
      Relicanth: "20%",
      Grimer: "20%",
    },
    "Super Rod [1F] (65)": {
      Whiscash: "40%",
      Muk: "40%",
      Gyarados: "15%",
      Staryu: "4%",
      Starmie: "1%",
    },
    "Cave [1F Room 2] (70)": {
      Wobbuffet: "20%",
      Electrode: "20%",
      Crobat: "10%",
      Solrock: "10%",
      Lunatone: "10%",
      Clefable: "10%",
      Clefairy: "5%",
      Metang: "5%",
      Shelgon: "4%",
      Bagon: "4%",
      Beldum: "2%",
    },
    "Surfing [1F Room 2] (70)": {
      Armaldo: "60%",
      Starmie: "30%",
      Solrock: "5%",
      Lunatone: "4%",
      Cradily: "1%",
    },
    "Old Rod [1F Room 2] (70)": { Seaking: "70%", Sharpedo: "30%" },
    "Good Rod [1F Room 2] (70)": {
      Politoed: "60%",
      Poliwrath: "20%",
      Golduck: "20%",
    },
    "Super Rod [1F Room 2] (70)": {
      Whiscash: "40%",
      Gyarados: "40%",
      Kingdra: "15%",
      Feebas: "4%",
      Lapras: "1%",
    },
    "Cave [B1F] (70)": {
      Crobat: "20%",
      Lunatone: "20%",
      Claydol: "10%",
      Solrock: "10%",
      Clefairy: "10%",
      Cleffa: "10%",
      Clefable: "5%",
      Aggron: "5%",
      Wobbuffet: "4%",
      Gardevoir: "4%",
      Flygon: "2%",
    },
    "Surfing [B1F] (70)": { Solrock: "100%" },
    "Old Rod [B1F] (70)": { Kabutops: "70%", Omastar: "30%" },
    "Good Rod [B1F] (70)": {
      Relicanth: "60%",
      Whiscash: "20%",
      Seaking: "20%",
    },
    "Super Rod [B1F] (70)": {
      Crawdaunt: "40%",
      Gyarados: "40%",
      Feebas: "15%",
      Staryu: "4%",
      Milotic: "1%",
    },
    "Cave [B1F Room 2] (70)": {
      Wobbuffet: "20%",
      Lunatone: "20%",
      Solrock: "10%",
      Dugtrio: "10%",
      Clefable: "10%",
      Clefairy: "10%",
      Claydol: "5%",
      Flygon: "5%",
      Salamence: "4%",
      Metagross: "4%",
      Pupitar: "1%",
      Larvitar: "1%",
    },
    "Surfing [B1F Room 2] (70)": {
      Gyarados: "60%",
      Solrock: "30%",
      Lapras: "5%",
      Lunatone: "4%",
      Dragonair: "1%",
    },
    "Old Rod [B1F Room 2] (70)": { Feebas: "100%" },
    "Good Rod [B1F Room 2] (70)": {
      Gyarados: "60%",
      Cradily: "20%",
      Armaldo: "20%",
    },
    "Super Rod [B1F Room 2] (70)": {
      Staryu: "40%",
      Dragonair: "40%",
      Milotic: "15%",
      Dratini: "5%",
    },
  },
  "Mt. Chimney": {},
  "Jagged Pass": {
    "Grass (36)": {
      Numel: "20%",
      Magcargo: "20%",
      Machoke: "10%",
      Spoink: "10%",
      Ponyta: "10%",
      Mankey: "10%",
      Koffing: "5%",
      Grimer: "5%",
      Doduo: "4%",
      Onix: "4%",
      Quilava: "1%",
      Rapidash: "1%",
    },
  },
  "Lavaridge Town": {
    "Gift (Egg)": { Wynaut: "100%" },
    "Grass (36)": {
      Torkoal: "20%",
      Vulpix: "20%",
      Magby: "15%",
      Ponyta: "14%",
      Growlithe: "10%",
      Flareon: "10%",
      Numel: "5%",
      Quilava: "4%",
      Charmeleon: "2%",
    },
  },
  "Mirage Tower": {
    "Tower [1F] (38)": {
      Cacnea: "20%",
      Trapinch: "20%",
      Sandshrew: "10%",
      Diglett: "10%",
      Phanpy: "10%",
      Numel: "10%",
      Baltoy: "5%",
      Cubone: "5%",
      Rhyhorn: "4%",
      Onix: "4%",
      Unown: "2%",
    },
    "Tower [2F] (39)": {
      Trapinch: "30%",
      Rhyhorn: "20%",
      Phanpy: "10%",
      Sandshrew: "10%",
      Camerupt: "10%",
      Sandslash: "5%",
      Dugtrio: "5%",
      Nosepass: "4%",
      Graveler: "4%",
      Claydol: "1%",
      Gligar: "1%",
    },
    "Tower [3F] (40)": {
      Dugtrio: "20%",
      Trapinch: "20%",
      Wobbuffet: "10%",
      Cacturne: "10%",
      Marowak: "10%",
      Donphan: "10%",
      Onix: "5%",
      Sandslash: "5%",
      Nidorino: "4%",
      Nidorina: "4%",
      Vibrava: "2%",
    },
    "Tower [4F] (10)": { Bagon: "100%" },
  },
  "Route 105": {
    "Surfing (43)": {
      Unown: "60%",
      Mantine: "30%",
      Octillery: "5%",
      Qwilfish: "4%",
      Relicanth: "1%",
    },
    "Old Rod (43)": { Octillery: "70%", Tentacruel: "30%" },
    "Good Rod (43)": {
      Gyarados: "60%",
      Qwilfish: "20%",
      Relicanth: "20%",
    },
    "Super Rod (65)": {
      Mantine: "40%",
      Relicanth: "40%",
      Sharpedo: "19%",
      Wailmer: "1%",
    },
    "Puzzle reward": { Regice: "100%" },
  },
  "Route 108": {
    "Surfing (43)": {
      Sharpedo: "60%",
      Tentacruel: "30%",
      Seviper: "5%",
      Qwilfish: "4%",
      Gyarados: "1%",
    },
    "Old Rod (44)": { Magikarp: "70%", Tentacool: "30%" },
    "Good Rod (44)": {
      Magikarp: "60%",
      Tentacool: "20%",
      Sharpedo: "20%",
    },
    "Super Rod (20-66)": { Sharpedo: "99%", Wailmer: "1%" },
  },
  "Route 134": {
    "Surfing (43)": {
      Horsea: "60%",
      Seadra: "31%",
      Remoraid: "5%",
      Seaking: "4%",
    },
    "Old Rod (43)": { Horsea: "70%", Seadra: "30%" },
    "Good Rod (43)": { Octillery: "60%", Remoraid: "40%" },
    "Super Rod (43)": {
      Corsola: "40%",
      Mantine: "40%",
      Horsea: "15%",
      Chinchou: "5%",
    },
  },
  "New Mauville": {
    "Cave [1F] (43)": {
      Electrode: "20%",
      Plusle: "20%",
      Minun: "10%",
      Magneton: "10%",
      Raichu: "10%",
      Manectric: "10%",
      Porygon: "5%",
      Electabuzz: "5%",
      Ampharos: "4%",
      Flaaffy: "4%",
      Voltorb: "1%",
      Pikachu: "1%",
    },
    "Cave [1F Room 2] (43)": {
      Electrode: "20%",
      Raichu: "20%",
      Magneton: "10%",
      Manectric: "10%",
      Muk: "10%",
      Porygon: "10%",
      Voltorb: "5%",
      Ampharos: "5%",
      Electabuzz: "4%",
      Porygon2: "4%",
      Pikachu: "1%",
      Jolteon: "1%",
    },
  },
  "Route 119": {
    "Grass (43)": {
      Zangoose: "20%",
      Tangela: "20%",
      Breloom: "10%",
      Absol: "10%",
      Seviper: "10%",
      Scyther: "10%",
      Linoone: "5%",
      Tropius: "5%",
      Furret: "4%",
      Raticate: "4%",
      Pinsir: "1%",
      Scizor: "1%",
    },
    "Surfing (43)": {
      Golduck: "60%",
      Pelipper: "30%",
      Whiscash: "5%",
      Carvanha: "4%",
      Feraligatr: "1%",
    },
    "Old Rod (44)": { Carvanha: "70%", Magikarp: "30%" },
    "Good Rod (44)": {
      Sharpedo: "60%",
      Politoed: "20%",
      Feraligatr: "20%",
    },
    "Super Rod (65)": {
      Gyarados: "40%",
      Poliwrath: "40%",
      Whiscash: "15%",
      Feraligatr: "4%",
      Blastoise: "1%",
    },
    "Gift (25)": { Castform: "100%" },
  },
  "Fortree City": {
    "Grass (47-50)": {
      Pidgeot: "20%",
      Fearow: "20%",
      Swellow: "14%",
      Pelipper: "10%",
      Noctowl: "10%",
      Tropius: "10%",
      Swablu: "5%",
      Altaria: "5%",
      Dodrio: "4%",
      Pineco: "1%",
      Shiftry: "1%",
    },
  },
  "Route 120": {
    "Grass (47)": {
      Scyther: "20%",
      Absol: "20%",
      Zangoose: "10%",
      Pinsir: "10%",
      Kecleon: "10%",
      Primeape: "10%",
      Tangela: "5%",
      Azumarill: "5%",
      Seviper: "4%",
      Spoink: "4%",
      Linoone: "1%",
      Scizor: "1%",
    },
    "Surfing (47)": {
      Azumarill: "60%",
      Fearow: "30%",
      Whiscash: "5%",
      Seaking: "4%",
      Golduck: "1%",
    },
    "Old Rod (49)": { Barboach: "70%", Seaking: "30%" },
    "Good Rod (49)": { Golduck: "60%", Kingler: "20%", Crawdaunt: "20%" },
    "Super Rod (65)": {
      Crawdaunt: "40%",
      Kingler: "40%",
      Slowpoke: "15%",
      Slowking: "4%",
      Slowbro: "1%",
    },
    "Puzzle reward": { Registeel: "100%" },
  },
  "Scorched Slab": {
    "Cave (50)": {
      Vulpix: "20%",
      Growlithe: "20%",
      Rapidash: "10%",
      Quilava: "10%",
      Charmeleon: "10%",
      Ninetales: "10%",
      Manectric: "5%",
      Magby: "5%",
      Magmar: "4%",
      Torkoal: "4%",
      Flareon: "1%",
      Arcanine: "1%",
    },
    "Surfing (50)": {
      Grimer: "60%",
      Koffing: "30%",
      Muk: "5%",
      Weezing: "5%",
    },
    "Old Rod (45)": { Grimer: "70%", Muk: "30%" },
    "Good Rod (50)": { Remoraid: "60%", Muk: "20%", Kingler: "20%" },
    "Super Rod (65)": {
      Crawdaunt: "40%",
      Octillery: "40%",
      Muk: "15%",
      Slowpoke: "5%",
    },
  },
  "Route 121": {
    "Grass (50)": {
      Absol: "20%",
      Exeggcute: "20%",
      Tropius: "10%",
      Exploud: "10%",
      Rapidash: "10%",
      Pidgeot: "10%",
      Stantler: "5%",
      Gloom: "5%",
      Weepinbell: "4%",
      Jumpluff: "4%",
      Arcanine: "1%",
      Pinsir: "1%",
    },
    "Surfing (50)": {
      Crawdaunt: "60%",
      Octillery: "30%",
      Tentacool: "5%",
      Pelipper: "5%",
    },
    "Old Rod (50)": { Seaking: "70%", Qwilfish: "30%" },
    "Good Rod (50)": { Mantine: "60%", Chinchou: "20%", Corsola: "20%" },
    "Super Rod (65)": {
      Octillery: "40%",
      Seviper: "40%",
      Tentacruel: "15%",
      Relicanth: "5%",
    },
  },
  "Lilycove City": {
    "Grass (55)": {
      Granbull: "20%",
      Jumpluff: "20%",
      Blastoise: "10%",
      Vileplume: "10%",
      Wigglytuff: "10%",
      Bellossom: "10%",
      Lickitung: "6%",
      Togetic: "5%",
      Feraligatr: "5%",
      Exploud: "4%",
    },
    "Surfing (55)": {
      Sharpedo: "60%",
      Crawdaunt: "30%",
      Kingler: "5%",
      Octillery: "4%",
      Blastoise: "1%",
    },
    "Old Rod (55)": { Sharpedo: "70%", Crawdaunt: "30%" },
    "Good Rod (55)": { Sharpedo: "60%", Qwilfish: "20%", Mantine: "20%" },
    "Super Rod (65)": {
      Sharpedo: "40%",
      Tentacruel: "40%",
      Cloyster: "15%",
      Gyarados: "4%",
      Lanturn: "1%",
    },
  },
  "Safari Zone": {
    "Grass [Area 1] (45-50)": {
      Vileplume: "20%",
      Granbull: "20%",
      Girafarig: "10%",
      Victreebel: "10%",
      Rapidash: "10%",
      Dodrio: "10%",
      Vigoroth: "5%",
      Forretress: "5%",
      Primeape: "4%",
      Grovyle: "4%",
      Ivysaur: "2%",
    },
    "Grass [Area 2] (50-56)": {
      Exeggutor: "20%",
      Rhydon: "20%",
      Miltank: "10%",
      Kangaskhan: "10%",
      Nidoqueen: "10%",
      Dodrio: "10%",
      Arbok: "5%",
      Zangoose: "5%",
      Sandslash: "4%",
      Venusaur: "4%",
      Ivysaur: "1%",
      Bulbasaur: "1%",
    },
    "Surfing [Area 2] (50)": { Psyduck: "90%", Golduck: "10%" },
    "Old Rod [Area 2] (52)": { Corphish: "70%", Crawdaunt: "30%" },
    "Good Rod [Area 2] (10-45)": {
      Ludicolo: "60%",
      Lombre: "20%",
      Lotad: "20%",
    },
    "Super Rod [Area 2] (25-65)": {
      Psyduck: "40%",
      Golduck: "40%",
      Seadra: "15%",
      Milotic: "4%",
      Feebas: "1%",
    },
    "Grass [Area 3] (42-55)": {
      Eevee: "20%",
      Flareon: "20%",
      Espeon: "10%",
      Umbreon: "10%",
      Vaporeon: "10%",
      Jolteon: "10%",
      Kangaskhan: "5%",
      Rhydon: "5%",
      Dodrio: "4%",
      Miltank: "4%",
      Tauros: "1%",
      Snorlax: "1%",
    },
    "Surfing [Area 3] (50)": {
      Omastar: "60%",
      Kabutops: "30%",
      Kabuto: "5%",
      Omanyte: "5%",
    },
    "Old Rod [Area 3] (40)": { Wartortle: "70%", Squirtle: "30%" },
    "Good Rod [Area 3] (10-50)": {
      Whiscash: "60%",
      Barboach: "20%",
      Wooper: "20%",
    },
    "Super Rod [Area 3] (25-46)": {
      Croconaw: "40%",
      Totodile: "40%",
      Quagsire: "15%",
      Marshtomp: "4%",
      Mudkip: "1%",
    },
    "Grass [Area 4] (27-56)": {
      Donphan: "20%",
      Arcanine: "20%",
      Nidoking: "10%",
      Scyther: "10%",
      Ursaring: "10%",
      Seviper: "10%",
      Tauros: "5%",
      Heracross: "5%",
      Bayleef: "4%",
      Grovyle: "4%",
      Chikorita: "1%",
      Treecko: "1%",
    },
    "Rock Smash [Area 4] (5-30)": { Geodude: "100%" },
  },
  "Route 122": {
    "Surfing (51)": {
      Golduck: "60%",
      Golbat: "30%",
      Sharpedo: "5%",
      Pelipper: "5%",
    },
    "Old Rod (50)": { Crawdaunt: "70%", Tentacruel: "30%" },
    "Good Rod (50)": { Gyarados: "60%", Sharpedo: "40%" },
    "Super Rod (65)": { Tentacruel: "55%", Gastly: "40%", Qwilfish: "5%" },
  },
  "Route 125": {
    "Surfing (64)": {
      Dewgong: "60%",
      Walrein: "30%",
      Cloyster: "5%",
      Slowking: "4%",
      Slowbro: "1%",
    },
    "Old Rod (64)": { Sealeo: "100%" },
    "Good Rod (64)": { Slowking: "60%", Slowbro: "20%", Shellder: "20%" },
    "Super Rod (64)": {
      Cloyster: "40%",
      Dewgong: "40%",
      Walrein: "15%",
      Sharpedo: "5%",
    },
  },
  "Shoal Cave": {
    "Cave [1F] (63-65)": {
      Spheal: "20%",
      Seel: "20%",
      Sealeo: "10%",
      Smoochum: "10%",
      Swinub: "10%",
      Slowpoke: "10%",
      Shellder: "5%",
      Delibird: "5%",
      Kingler: "4%",
      Golduck: "4%",
      Cloyster: "1%",
      Walrein: "1%",
    },
    "Surfing [1F] (64)": {
      Sealeo: "60%",
      Dewgong: "30%",
      Shellder: "5%",
      Slowbro: "4%",
      Walrein: "1%",
    },
    "Old Rod [1F] (65)": { Shellder: "70%", Seel: "30%" },
    "Good Rod [1F] (65)": { Seel: "60%", Spheal: "20%", Shellder: "20%" },
    "Super Rod [1F] (4-65)": {
      Sealeo: "40%",
      Dewgong: "40%",
      Walrein: "15%",
      Cloyster: "4%",
      Wailmer: "1%",
    },
    "Cave [1F Room 2] (64)": {
      Swinub: "20%",
      Sealeo: "20%",
      Smoochum: "10%",
      Seel: "10%",
      Shellder: "10%",
      Delibird: "10%",
      Sneasel: "5%",
      Kingler: "5%",
      Slowking: "4%",
      Slowbro: "4%",
      Jynx: "1%",
      Walrein: "1%",
    },
    "Surfing [1F Room 2] (64-65)": {
      Dewgong: "60%",
      Slowking: "30%",
      Slowbro: "5%",
      Cloyster: "4%",
      Walrein: "1%",
    },
    "Old Rod [1F Room 2] (65)": { Shellder: "70%", Clamperl: "30%" },
    "Good Rod [1F Room 2] (65)": { Seel: "60%", Sealeo: "40%" },
    "Super Rod [1F Room 2] (4-65)": {
      Dewgong: "40%",
      Cloyster: "40%",
      Walrein: "19%",
      Wailmer: "1%",
    },
    "Cave [1F Room 3] (64)": {
      Snorunt: "20%",
      Smoochum: "20%",
      Swinub: "10%",
      Seel: "10%",
      Sealeo: "10%",
      Shellder: "10%",
      Slowpoke: "5%",
      Cloyster: "5%",
      Jynx: "4%",
      Glalie: "4%",
      Piloswine: "1%",
      Walrein: "1%",
    },
    "Cave [B1F] (65)": {
      Piloswine: "20%",
      Glalie: "20%",
      Jynx: "10%",
      Seel: "10%",
      Sealeo: "10%",
      Slowpoke: "10%",
      Slowking: "5%",
      Slowbro: "5%",
      Delibird: "4%",
      Swinub: "4%",
      Smoochum: "1%",
      Snorunt: "1%",
    },
    "Cave [B1F Ice] (63-65)": {
      Dugtrio: "20%",
      Jynx: "20%",
      Dewgong: "10%",
      Cloyster: "10%",
      Piloswine: "10%",
      Glalie: "10%",
      Walrein: "5%",
      Slowbro: "5%",
      Slowking: "4%",
      Wobbuffet: "4%",
      Hariyama: "1%",
      Lapras: "1%",
    },
  },
  "Route 124": {
    "Surfing (63)": {
      Qwilfish: "60%",
      Mantine: "30%",
      Tentacruel: "5%",
      Pelipper: "5%",
    },
    "Old Rod (63)": { Corsola: "70%", Seaking: "30%" },
    "Good Rod (63)": {
      Qwilfish: "60%",
      Remoraid: "20%",
      Tentacruel: "20%",
    },
    "Super Rod (63)": {
      Sharpedo: "40%",
      Octillery: "40%",
      Mantine: "15%",
      Lanturn: "5%",
    },
    "Diving (68)": {
      Kabutops: "60%",
      Omastar: "30%",
      Lanturn: "5%",
      Relicanth: "4%",
      Kingdra: "1%",
    },
  },
  "Route 126": {
    "Surfing (65)": {
      Poliwrath: "60%",
      Feraligatr: "30%",
      Blastoise: "5%",
      Seaking: "5%",
    },
    "Old Rod (65)": { Slowpoke: "100%" },
    "Good Rod (65)": {
      Slowbro: "60%",
      Qwilfish: "20%",
      Tentacruel: "20%",
    },
    "Super Rod (65)": {
      Sharpedo: "40%",
      Corsola: "40%",
      Gyarados: "15%",
      Octillery: "5%",
    },
    "Diving (68)": {
      Huntail: "60%",
      Lanturn: "30%",
      Gorebyss: "5%",
      Armaldo: "4%",
      Cradily: "1%",
    },
  },
  "Sootopolis City": {
    "Grass (5-60)": {
      Heracross: "40%",
      Lotad: "29%",
      Lombre: "29%",
      Ludicolo: "2%",
    },
    "Surfing (70)": {
      Mantine: "60%",
      Relicanth: "30%",
      Octillery: "5%",
      Magikarp: "5%",
    },
    "Old Rod (70)": { Seaking: "70%", Relicanth: "30%" },
    "Good Rod (70)": {
      Huntail: "60%",
      Kabutops: "20%",
      Relicanth: "20%",
    },
    "Super Rod (70)": {
      Armaldo: "40%",
      Omastar: "40%",
      Gorebyss: "15%",
      Cradily: "5%",
    },
  },
  "Route 127": {
    "Surfing (65)": {
      Sharpedo: "60%",
      Mantine: "30%",
      Qwilfish: "5%",
      Tentacruel: "5%",
    },
    "Old Rod (65)": { Octillery: "70%", Slowbro: "30%" },
    "Good Rod (65)": {
      Qwilfish: "60%",
      Mantine: "20%",
      Tentacruel: "20%",
    },
    "Super Rod (65)": {
      Sharpedo: "40%",
      Kabutops: "40%",
      Omastar: "15%",
      Lanturn: "5%",
    },
  },
  "Route 128": {
    "Surfing (65)": {
      Sharpedo: "60%",
      Lanturn: "30%",
      Tentacruel: "5%",
      Jumpluff: "4%",
      Gyarados: "1%",
    },
    "Old Rod (65)": { Clamperl: "100%" },
    "Good Rod (65)": { Cloyster: "60%", Huntail: "20%", Gorebyss: "20%" },
    "Super Rod (65)": {
      Corsola: "40%",
      Octillery: "40%",
      Relicanth: "15%",
      Armaldo: "4%",
      Cradily: "1%",
    },
  },
  "Seafloor Cavern": {
    "Surfing [Room 1] (67)": {
      Crobat: "60%",
      Gyarados: "30%",
      Feraligatr: "5%",
      Tentacruel: "5%",
    },
    "Old Rod [Room 1] (65)": { Huntail: "70%", Gorebyss: "30%" },
    "Good Rod [Room 1] (65)": {
      Tentacruel: "60%",
      Qwilfish: "20%",
      Feraligatr: "20%",
    },
    "Super Rod [Room 1] (65)": {
      Blastoise: "40%",
      Sharpedo: "40%",
      Relicanth: "15%",
      Walrein: "5%",
    },
    "Cave [Room 2] (66)": {
      Crawdaunt: "20%",
      Wobbuffet: "20%",
      Crobat: "10%",
      Muk: "10%",
      Gengar: "10%",
      Dugtrio: "10%",
      Feraligatr: "5%",
      Kingler: "5%",
      Blastoise: "4%",
      Seviper: "4%",
      Kabutops: "2%",
    },
    "Cave [Room 3] (68)": {
      Wobbuffet: "20%",
      Dugtrio: "20%",
      Omastar: "10%",
      Kabutops: "10%",
      Crobat: "10%",
      Muk: "10%",
      Cloyster: "5%",
      Crawdaunt: "5%",
      Kingler: "4%",
      Steelix: "4%",
      Claydol: "2%",
    },
    "Cave [Room 4] (68)": {
      Wobbuffet: "22%",
      Dugtrio: "20%",
      Seviper: "10%",
      Dunsparce: "10%",
      Crobat: "10%",
      Feraligatr: "10%",
      Blastoise: "5%",
      Electrode: "5%",
      Glalie: "4%",
      Steelix: "4%",
    },
    "Cave [Room 5] (68)": {
      Dugtrio: "20%",
      Wobbuffet: "20%",
      Parasect: "10%",
      Feraligatr: "10%",
      Ariados: "10%",
      Crobat: "10%",
      Seviper: "5%",
      Muk: "5%",
      Crawdaunt: "4%",
      Misdreavus: "4%",
      Vaporeon: "2%",
    },
    "Cave [Room 6] (68)": {
      Wobbuffet: "20%",
      Glalie: "20%",
      Jynx: "10%",
      Piloswine: "10%",
      Walrein: "10%",
      Dugtrio: "10%",
      Armaldo: "5%",
      Dewgong: "5%",
      Misdreavus: "4%",
      Gyarados: "4%",
      Dunsparce: "1%",
      Steelix: "1%",
    },
    "Surfing [Room 6] (66-69)": {
      Gorebyss: "60%",
      Cloyster: "30%",
      Dewgong: "5%",
      Walrein: "4%",
      Lapras: "1%",
    },
    "Old Rod [Room 6] (68)": { Walrein: "70%", Tentacruel: "30%" },
    "Good Rod [Room 6] (68)": {
      Dewgong: "60%",
      Cloyster: "20%",
      Qwilfish: "20%",
    },
    "Super Rod [Room 6] (68)": {
      Sharpedo: "40%",
      Huntail: "40%",
      Gorebyss: "15%",
      Lapras: "4%",
      Wailmer: "1%",
    },
    "Cave [Room 7] (68)": { Wobbuffet: "100%" },
    "Surfing [Room 7] (68)": {
      Qwilfish: "60%",
      Mantine: "30%",
      Gorebyss: "5%",
      Huntail: "4%",
      Dewgong: "1%",
    },
    "Old Rod [Room 7] (67)": { Seviper: "70%", Gorebyss: "30%" },
    "Good Rod [Room 7] (67)": {
      Muk: "60%",
      Tentacruel: "20%",
      Mantine: "20%",
    },
    "Super Rod [Room 7] (67)": {
      Muk: "40%",
      Mantine: "40%",
      Lapras: "15%",
      Wailmer: "4%",
      Wailord: "1%",
    },
    "Cave [Room 8] (68)": {
      Wobbuffet: "26%",
      Dugtrio: "20%",
      Gengar: "10%",
      Muk: "10%",
      Huntail: "10%",
      Gorebyss: "10%",
      Steelix: "5%",
      Gyarados: "5%",
      Octillery: "4%",
    },
    "Cave [Room 9] (70)": { Wobbuffet: "100%" },
  },
  "Cave of Origin": {
    "Cave [1F] (70)": {
      Misdreavus: "20%",
      Xatu: "20%",
      Marowak: "10%",
      Banette: "10%",
      Kadabra: "10%",
      Absol: "10%",
      Haunter: "5%",
      Persian: "5%",
      Hypno: "4%",
      Crobat: "4%",
      Gardevoir: "1%",
      undefined: "Gengar",
    },
    "Cave [1F Room 2] (61-70)": {
      Wobbuffet: "20%",
      Crobat: "20%",
      Parasect: "10%",
      Banette: "10%",
      Armaldo: "10%",
      Cradily: "10%",
      Omastar: "5%",
      Kabutops: "5%",
      Marowak: "4%",
      Ninetales: "4%",
      Duskull: "1%",
      Dusclops: "1%",
    },
    "Cave [B1F] (60-70)": {
      Wobbuffet: "20%",
      Crobat: "20%",
      Gardevoir: "10%",
      Dunsparce: "10%",
      Armaldo: "10%",
      Cradily: "10%",
      Banette: "5%",
      Gengar: "5%",
      Misdreavus: "4%",
      Houndour: "4%",
      Dusclops: "1%",
    },
    "Cave [B2F] (5-66)": { Duskull: "98%", Dusclops: "2%" },
    "Cave [B3F] (30-71)": {
      Wobbuffet: "20%",
      Crobat: "20%",
      Ninetales: "10%",
      Gardevoir: "10%",
      Alakazam: "10%",
      Dugtrio: "10%",
      Marowak: "5%",
      Misdreavus: "5%",
      Duskull: "4%",
      Gengar: "4%",
      Houndoom: "1%",
      Aerodactyl: "1%",
    },
  },
  "Route 129": {
    "Surfing (65)": {
      Pelipper: "60%",
      Qwilfish: "30%",
      Octillery: "5%",
      Tentacruel: "4%",
      Gyarados: "1%",
    },
    "Old Rod (65)": { Mantine: "70%", Omastar: "30%" },
    "Good Rod (65)": {
      Kabutops: "60%",
      Sharpedo: "20%",
      Tentacruel: "20%",
    },
    "Super Rod (65)": {
      Relicanth: "40%",
      Lanturn: "40%",
      Armaldo: "15%",
      Cradily: "5%",
    },
  },
  "Route 130": {
    "Grass (63)": {
      Sableye: "20%",
      Shuckle: "20%",
      Tauros: "10%",
      Snorlax: "10%",
      Blissey: "10%",
      Dusclops: "10%",
      Shedinja: "5%",
      Ninjask: "5%",
      Tyranitar: "4%",
      Salamence: "4%",
      Metagross: "1%",
      Dragonite: "1%",
    },
    "Surfing (65)": {
      Qwilfish: "60%",
      Mantine: "30%",
      Huntail: "5%",
      Dewgong: "4%",
      Gorebyss: "1%",
    },
    "Old Rod (65)": { Dewgong: "70%", Tentacruel: "30%" },
    "Good Rod (65)": { Mantine: "60%", Gyarados: "20%", Slowking: "20%" },
    "Super Rod (65)": {
      Sharpedo: "40%",
      Slowbro: "40%",
      Octillery: "15%",
      Relicanth: "5%",
    },
  },
  "Route 131": {
    "Surfing (65)": {
      Qwilfish: "60%",
      Mantine: "30%",
      Misdreavus: "5%",
      Dewgong: "4%",
      Altaria: "1%",
    },
    "Old Rod (65)": { Corsola: "70%", Sharpedo: "30%" },
    "Good Rod (65)": {
      Mantine: "60%",
      Gyarados: "20%",
      Tentacruel: "20%",
    },
    "Super Rod (65)": {
      Relicanth: "40%",
      Qwilfish: "40%",
      Tentacruel: "15%",
      Lanturn: "5%",
    },
  },
  "Pacifidlog Town": {
    "Surfing (66)": {
      Octillery: "60%",
      Mantine: "30%",
      Blastoise: "5%",
      Relicanth: "4%",
      Corsola: "1%",
    },
    "Old Rod (65)": { Huntail: "70%", Corsola: "30%" },
    "Good Rod (65)": {
      Sharpedo: "60%",
      Relicanth: "20%",
      Gorebyss: "20%",
    },
    "Super Rod (65)": {
      Kabutops: "40%",
      Clamperl: "40%",
      Cloyster: "15%",
      Omastar: "4%",
      Seadra: "1%",
    },
  },
  "Sky Pillar": {
    "Tower [1F] (70)": {
      Gengar: "20%",
      Xatu: "20%",
      Dugtrio: "10%",
      Altaria: "10%",
      Shiftry: "10%",
      Flygon: "10%",
      Banette: "5%",
      Claydol: "5%",
      Misdreavus: "4%",
      Unown: "4%",
      Crobat: "1%",
      Noctowl: "1%",
    },
    "Tower [3F] (70)": {
      Wobbuffet: "20%",
      Crobat: "20%",
      Dugtrio: "10%",
      Gengar: "10%",
      Claydol: "10%",
      Electrode: "10%",
      Banette: "5%",
      Charizard: "5%",
      Noctowl: "4%",
      Swellow: "4%",
      Flygon: "2%",
    },
    "Tower [5F] (33-39)": {
      Wobbuffet: "20%",
      Electrode: "20%",
      Dugtrio: "10%",
      Crobat: "10%",
      Castform: "10%",
      Banette: "10%",
      Venomoth: "5%",
      Xatu: "5%",
      Claydol: "4%",
      Altaria: "4%",
      Flygon: "1%",
      Unown: "1%",
    },
  },
  "Route 132": {
    "Surfing (60-65)": {
      Tentacruel: "60%",
      Relicanth: "30%",
      Seadra: "5%",
      Staryu: "4%",
      Wailmer: "1%",
    },
    "Old Rod (65)": { Clamperl: "70%", Cloyster: "30%" },
    "Good Rod (65)": { Mantine: "60%", Qwilfish: "20%", Staryu: "20%" },
    "Super Rod (40-66)": {
      Sharpedo: "40%",
      Lanturn: "40%",
      Tentacruel: "15%",
      Luvdisc: "4%",
      Wailmer: "1%",
    },
  },
  "Route 133": {
    "Surfing (60-66)": { Mantine: "70%", Qwilfish: "30%" },
    "Old Rod (66)": { Blastoise: "60%", Seadra: "20%", Wailmer: "20%" },
    "Good Rod (10-66)": {
      Blastoise: "60%",
      Seadra: "20%",
      Wailmer: "20%",
    },
    "Super Rod (20-66)": {
      Sharpedo: "40%",
      Wailmer: "40%",
      Kingdra: "15%",
      Lapras: "4%",
      Wailord: "1%",
    },
  },
  "Route 123": {
    "Grass (74)": {
      Wobbuffet: "20%",
      Tauros: "20%",
      Ludicolo: "10%",
      Arcanine: "10%",
      Medicham: "10%",
      Slaking: "10%",
      Skarmory: "5%",
      Duskull: "5%",
      Miltank: "4%",
      Heracross: "4%",
      Snorlax: "2%",
    },
    "Surfing (52)": {
      Crawdaunt: "60%",
      Qwilfish: "30%",
      Sharpedo: "5%",
      Gyarados: "4%",
      Lombre: "1%",
    },
    "Old Rod (55)": { Qwilfish: "70%", Lombre: "30%" },
    "Good Rod (55)": {
      Gyarados: "60%",
      Kingler: "20%",
      Feraligatr: "20%",
    },
    "Super Rod (65)": {
      Crawdaunt: "40%",
      Seaking: "40%",
      Clamperl: "15%",
      Blastoise: "5%",
    },
  },
  "Ever Grande City": {
    "Grass (70)": {
      Torchic: "25%",
      Treecko: "25%",
      Combusken: "10%",
      Grovyle: "10%",
      Blaziken: "10%",
      Sceptile: "10%",
      Eevee: "4%",
      Marshtomp: "4%",
      Mudkip: "1%",
      Swampert: "1%",
    },
    "Surfing (65)": {
      Blastoise: "60%",
      Feraligatr: "30%",
      Gyarados: "5%",
      Sharpedo: "4%",
      Lanturn: "1%",
    },
    "Old Rod (65)": { Sharpedo: "70%", Mantine: "30%" },
    "Good Rod (65)": {
      Tentacruel: "60%",
      Qwilfish: "20%",
      Gyarados: "20%",
    },
    "Super Rod (65)": { Luvdisc: "81%", Corsola: "19%" },
  },
  "Victory Road": {
    "Cave [1F] (72)": {
      Wobbuffet: "20%",
      Crobat: "20%",
      Electrode: "10%",
      Dodrio: "10%",
      Dugtrio: "10%",
      Medicham: "10%",
      Kangaskhan: "5%",
      Jynx: "5%",
      Electabuzz: "4%",
      "Mr.": "4%",
      Exploud: "2%",
    },
    "Cave [B1F] (72)": {
      Wobbuffet: "20%",
      Dugtrio: "20%",
      Electrode: "10%",
      Crobat: "10%",
      Banette: "10%",
      Machamp: "10%",
      Blastoise: "5%",
      Hariyama: "5%",
      Golem: "4%",
      Hypno: "4%",
      Venomoth: "2%",
    },
    "Rock Smash [B1F] (30-40)": { Graveler: "70%", Geodude: "30%" },
    "Cave [B2F] (73)": {
      Electrode: "20%",
      Wobbuffet: "20%",
      Crobat: "10%",
      Dugtrio: "10%",
      Muk: "10%",
      Golduck: "10%",
      Arcanine: "5%",
      Nidoking: "5%",
      Ursaring: "4%",
      Grumpig: "4%",
      Granbull: "2%",
    },
    "Surfing [B2F] (73)": {
      Crobat: "60%",
      Muk: "30%",
      Sharpedo: "5%",
      Weezing: "5%",
    },
    "Old Rod [B2F]": { Crawdaunt: "70%", Gyarados: "30%" },
    "Good Rod [B2F] (73)": {
      Whiscash: "60%",
      Relicanth: "20%",
      Tentacruel: "20%",
    },
    "Super Rod [B2F] (73)": {
      Muk: "40%",
      Feraligatr: "40%",
      Blastoise: "15%",
      Lapras: "4%",
      Quagsire: "1%",
    },
  },
};
